using UnityEngine;

/// <summary>
/// Listens to <see cref="PopupMenuManager.OnLodChange"/> and forces all
/// <see cref="LODGroup"/> components in the active patent to a specific LOD level.
/// LOD 0 = full quality; LOD 1 = simplified mesh generated by <see cref="GenerateLOD"/>.
/// </summary>
public class LodManager : MonoBehaviour
{
    [SerializeField] private PopupMenuManager popupMenuManager;

    /// <summary>Subscribes to <see cref="PopupMenuManager.OnLodChange"/>.</summary>
    private void Start()
    {
        if (popupMenuManager != null)
            popupMenuManager.OnLodChange += OnLodChange;
        else
            Debug.LogError("PopupMenuManager is null on LodManager");
    }

    /// <summary>Unsubscribes from <see cref="PopupMenuManager.OnLodChange"/> to prevent dangling callbacks.</summary>
    private void OnDestroy()
    {
        if (popupMenuManager != null)
            popupMenuManager.OnLodChange -= OnLodChange;
    }

    /// <summary>
    /// Forces every <see cref="LODGroup"/> in the active patent to LOD 1 (simplified)
    /// when <paramref name="isOn"/> is <c>true</c>, or LOD 0 (full quality) when <c>false</c>.
    /// </summary>
    /// <param name="isOn"><c>true</c> to enable the lower-quality LOD.</param>
    private void OnLodChange(bool isOn)
    {
        GameObject patent = PatentManager.Instance?.ActivePatent;
        if (patent == null) return;

        int targetLod = isOn ? 1 : 0;
        foreach (LODGroup lodGroup in patent.GetComponentsInChildren<LODGroup>())
            lodGroup.ForceLOD(targetLod);
    }
}
